### ISSUE TITLE
Plotting Odas Data

### ISSUE THREAD

**Issue by Anamtya2024** [BratYanek/SSL_Triangulation#1]
Hi Yanek,

I am working on ODAS and saw your issue there.. I am saving the data from ODAS in a JSON file and want to calculate the azi and elevation from there.

Can you please guide me on how i can use your SSL code?

Thanks

**Comment by BratYanek** [comment]
Hi Anamtya,

Could you please show me what your saved data output looks like?

**Comment by BratYanek** [comment]
Hi Anamtya,

Could you please show me what your saved data output looks like?

**Comment by Anamtya2024** [comment]
hi,

thanks for the reply, however i was able to resolve the issue,

the json had some missing commas, which i was able to add back to the code

thanks
